server:
  port: 8082


spring:
  application:
    name: eureka-feign

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/