server:
  port: 8083


spring:
  application:
    name: eureka-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/

feign:
  hystrix:
    enabled: true