server:
  port: 8762

eureka:
  instance:
    hostname: eureka
  server:
#    enable-self-preservation: false #关闭自我保护机制, 生产环境需关闭
    eviction-interval-timer-in-ms: 10000 # 清理间隔（单位毫秒，默认是60*1000）
    renewal-percent-threshold: 0.6 # renews 和renews threshold的比值, 低于此值进入保护模式
  client:
#    register-with-eureka: false #false代表不向注册中心注册自己（因为本身就是注册中心）
#    fetch-registry: false #注册中心用于维护服务实例，无需检索服务
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

spring:
  freemarker:
    prefer-file-system-access: false # eureka dashboard returns XML

# eureka user-password
security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123456